/*
 * CANARY provisioning tool.
 *
 * Run this ONCE, offline, on a laptop (not on any ESP32). It generates
 * one Ed25519 keypair per legitimate node (1, 2, 6) using the exact same
 * Monocypher EdDSA implementation the firmware uses -- deliberately not
 * Python/pynacl/pycryptodome, because Monocypher's EdDSA uses BLAKE2b
 * internally rather than SHA-512, so a different library would produce
 * keys/signatures that are NOT interoperable with what the firmware
 * verifies.
 *
 * Output: canary_secrets.h, containing:
 *   - each node's secret key (to be flashed ONLY onto that node)
 *   - each node's public key (to be flashed onto Node 4, the verifier)
 *
 * This file is provisioning output, not something to commit to a public
 * repo -- treat canary_secrets.h as a credential.
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <time.h>
#include "canary_crypto.h"

static void random_seed(uint8_t seed[CANARY_SEED_LEN]) {
    /* NOTE: rand() is NOT a cryptographically secure RNG. This is fine
     * for a benchtop demo's provisioning step, but a real deployment
     * must use a proper CSPRNG (e.g. /dev/urandom, or the ESP32's
     * hardware RNG if provisioning on-device instead of on a laptop). */
    for (int i = 0; i < CANARY_SEED_LEN; i++) {
        seed[i] = (uint8_t)(rand() & 0xFF);
    }
}

static void print_hex_array(FILE *f, const char *name, const uint8_t *buf, size_t len) {
    fprintf(f, "static const uint8_t %s[%zu] = {", name, len);
    for (size_t i = 0; i < len; i++) {
        if (i % 12 == 0) fprintf(f, "\n    ");
        fprintf(f, "0x%02x, ", buf[i]);
    }
    fprintf(f, "\n};\n\n");
}

typedef struct { int id; const char *label; } node_def_t;

int main(void) {
    srand((unsigned)time(NULL));

    node_def_t nodes[] = {
        {1, "ENCODER"},
        {2, "IMU"},
        {6, "GATEWAY"},
    };
    const int n_nodes = sizeof(nodes) / sizeof(nodes[0]);

    FILE *f = fopen("canary_secrets.h", "w");
    if (!f) { perror("fopen"); return 1; }

    fprintf(f, "/* AUTO-GENERATED by provision.c -- do not hand-edit. */\n");
    fprintf(f, "#ifndef CANARY_SECRETS_H\n#define CANARY_SECRETS_H\n\n");
    fprintf(f, "#include <stdint.h>\n\n");

    for (int i = 0; i < n_nodes; i++) {
        uint8_t seed[CANARY_SEED_LEN];
        uint8_t sk[CANARY_SECRET_KEY_LEN];
        uint8_t pk[CANARY_PUBLIC_KEY_LEN];

        random_seed(seed);
        canary_keygen(sk, pk, seed);

        char sk_name[64], pk_name[64];
        snprintf(sk_name, sizeof(sk_name), "NODE%d_%s_SECRET_KEY", nodes[i].id, nodes[i].label);
        snprintf(pk_name, sizeof(pk_name), "NODE%d_%s_PUBLIC_KEY", nodes[i].id, nodes[i].label);

        fprintf(f, "/* --- Node %d (%s) --- */\n", nodes[i].id, nodes[i].label);
        fprintf(f, "/* Flash the secret key ONLY onto Node %d itself. */\n", nodes[i].id);
        print_hex_array(f, sk_name, sk, CANARY_SECRET_KEY_LEN);
        fprintf(f, "/* Flash the public key onto Node 4 (Security ECU). */\n");
        print_hex_array(f, pk_name, pk, CANARY_PUBLIC_KEY_LEN);

        printf("Node %d (%s): keypair generated.\n", nodes[i].id, nodes[i].label);
    }

    fprintf(f, "#endif /* CANARY_SECRETS_H */\n");
    fclose(f);

    printf("\nWrote canary_secrets.h -- split this by hand before flashing:\n");
    printf("  each node gets ONLY its own secret key;\n");
    printf("  Node 4 gets ALL public keys, no secret keys.\n");
    return 0;
}
